// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGtKC1l4SWx3bwZ_lTsMrlZn8a4Mz6oc',
    appId: '1:752974853469:web:56b251b2fd12cd7faf64b4',
    messagingSenderId: '752974853469',
    projectId: 'fir-version-2b0c8',
    authDomain: 'fir-version-2b0c8.firebaseapp.com',
    storageBucket: 'fir-version-2b0c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfqSpeeQR65wLbcfJ6-tfGnd43HLCXtE',
    appId: '1:752974853469:android:6a50436512e82e77af64b4',
    messagingSenderId: '752974853469',
    projectId: 'fir-version-2b0c8',
    storageBucket: 'fir-version-2b0c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3D14eUZlkLK9Kb9lPJ5-y0h8aihoqgY',
    appId: '1:752974853469:ios:ec32b13203a7755aaf64b4',
    messagingSenderId: '752974853469',
    projectId: 'fir-version-2b0c8',
    storageBucket: 'fir-version-2b0c8.appspot.com',
    iosBundleId: 'com.skyforge.moment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE3D14eUZlkLK9Kb9lPJ5-y0h8aihoqgY',
    appId: '1:752974853469:ios:ec32b13203a7755aaf64b4',
    messagingSenderId: '752974853469',
    projectId: 'fir-version-2b0c8',
    storageBucket: 'fir-version-2b0c8.appspot.com',
    iosBundleId: 'com.skyforge.moment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBGtKC1l4SWx3bwZ_lTsMrlZn8a4Mz6oc',
    appId: '1:752974853469:web:c63573933e46d6c7af64b4',
    messagingSenderId: '752974853469',
    projectId: 'fir-version-2b0c8',
    authDomain: 'fir-version-2b0c8.firebaseapp.com',
    storageBucket: 'fir-version-2b0c8.appspot.com',
  );
}
